### ISSUE TITLE
tRPC Playground

### ISSUE THREAD

**Issue by oscartbeaumont** [sachinraja/trpc-pokemon#3]
It would be really cool if you added tRPC Playground so anyone can explore the schema online.

Love the project, it's nice to have a public tRPC API for testing stuff!

**Comment by sachinraja** [comment]
Good idea! Will try to get one up. Needs to add support for the Fetch API in tRPC Playground first though.

**Comment by sachinraja** [comment]
Got a playground up! https://pokemon.s4n.land/play
